language: python

python:
  - 3.6

before_install:
  # install libgit2
  - wget https://github.com/libgit2/libgit2/archive/v0.26.0.tar.gz
  - tar xzf v0.26.0.tar.gz
  - cd libgit2-0.26.0/
  - cmake .
  - make
  - sudo make install
  - cd ../

install:
  - pip install -r requirements.txt
  - pip install flake8
  # dynamic linker for libgit2 library
  - sudo ldconfig

before_script:

  - flake8 --exclude=migrations,libgit2-0.26.0,_site --max-line-length=122 .

script:
  - python manage.py migrate
  - python manage.py test
